# Uncomment the next line to define a global platform for your project
platform :ios, '14.0'

# 使用清华大学源（稳定）
source 'https://mirrors.tuna.tsinghua.edu.cn/git/CocoaPods/Specs.git'

use_frameworks!

target 'WeightLossBetting' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for WeightLossBetting
  
  # Networking - 网络请求
  pod 'Alamofire', '~> 5.8'
  
  # Image Loading - 图片加载
  pod 'Kingfisher', '~> 7.10'
  
  # Charts for progress visualization - 图表展示
  pod 'Charts', '~> 4.0'
  
  # Keychain for secure storage - 安全存储
  pod 'KeychainAccess', '~> 4.2'
  
  # UI Components - UI组件
  pod 'SnapKit', '~> 5.0'
  pod 'IQKeyboardManagerSwift', '~> 6.5'
  pod 'Toast-Swift', '~> 5.0'
  
  # Google Sign In - 谷歌登录
  pod 'GoogleSignIn', '~> 7.0'

  target 'WeightLossBettingTests' do
    inherit! :search_paths
    # Pods for testing
  end



end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.0'
    end
  end
end
