的# Uncomment the next line to define a global platform for your project
platform :ios, '14.0'

target 'WeightLossBetting' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for WeightLossBetting
  
  # Networking
  pod 'Alamofire', '~> 5.8'
  
  # Image Loading
  pod 'Kingfisher', '~> 7.10'
  
  # Stripe SDK for payments
  pod 'StripePaymentSheet', '~> 23.0'
  
  # Firebase Cloud Messaging
  pod 'Firebase/Messaging', '~> 10.20'
  
  # Google Sign-In
  pod 'GoogleSignIn', '~> 7.0'

  # Charts for progress visualization
  pod 'Charts', '~> 5.0'
  
  # Keychain for secure storage
  pod 'KeychainAccess', '~> 4.2'
  
  # UI Components
  pod 'SnapKit', '~> 5.0'
  pod 'IQKeyboardManagerSwift', '~> 6.5'

  target 'WeightLossBettingTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'WeightLossBettingUITests' do
    # Pods for testing
  end

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.0'
    end
  end
end
